include:
  - ../docker-compose-network.yaml

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.1.0
    volumes:
      - ./node:/ipc
      - ./db:/data/db
    environment:
      - NETWORK=preprod
    restart: always

  hydra-node-1:
    image: ghcr.io/cardano-scaling/hydra-node:0.18.1
    volumes:
      - ./credentials:/credentials:ro
      - ./node:/node
      - ./node-1-persistence:/persistence
    ports:
      - "4001:4001"
    command:
      [
        "--node-id",
        "1",
        "--api-host",
        "0.0.0.0",
        "--host",
        "172.16.238.10",
        "--monitoring-port",
        "6001",
        "--peer",
        "hydra-node-2:5001",
        "--hydra-scripts-tx-id",
        "976b28bc716490fbaa4e17d7bf33b04f27fcfafef58c436c4f2644adeeb48829",
        "--persistence-dir",
        "/persistence",
        "--hydra-signing-key",
        "/credentials/hydra-node-1.sk",
        "--hydra-verification-key",
        "/credentials/hydra-node-2.vk",
        "--cardano-signing-key",
        "/credentials/cardano-node-1.sk",
        "--cardano-verification-key",
        "/credentials/cardano-node-2.vk",
        "--ledger-protocol-parameters",
        "/node/protocol-parameters.json",
        "--testnet-magic",
        "1",
        "--node-socket",
        "/node/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-2:
    image: ghcr.io/cardano-scaling/hydra-node:0.18.1
    volumes:
      - ./credentials:/credentials:ro
      - ./node:/node
      - ./node-2-persistence:/persistence
    ports:
      - "4002:4001"
    command:
      [
        "--node-id",
        "2",
        "--api-host",
        "0.0.0.0",
        "--host",
        "172.16.238.20",
        "--monitoring-port",
        "6001",
        "--peer",
        "hydra-node-1:5001",
        "--hydra-scripts-tx-id",
        "976b28bc716490fbaa4e17d7bf33b04f27fcfafef58c436c4f2644adeeb48829",
        "--persistence-dir",
        "/persistence",
        "--hydra-signing-key",
        "/credentials/hydra-node-2.sk",
        "--hydra-verification-key",
        "/credentials/hydra-node-1.vk",
        "--cardano-signing-key",
        "/credentials/cardano-node-2.sk",
        "--cardano-verification-key",
        "/credentials/cardano-node-1.vk",
        "--ledger-protocol-parameters",
        "/node/protocol-parameters.json",
        "--testnet-magic",
        "1",
        "--node-socket",
        "/node/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always
